version: "3.8"

services:
  fastapi:
    build: .
    container_name: bsnap-app
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: bsnap-postgres
    environment:
      POSTGRES_DB: bsnap_db
      POSTGRES_USER: bsnap_user
      POSTGRES_PASSWORD: bsnap_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: bsnap-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: wijaya.indra2196@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  pgloader:
    image: dimitri/pgloader:latest
    profiles: ["migrate"]  # <--- hanya jalan kalau kamu minta
    volumes:
      - ./app:/app:ro
    entrypoint: >
      pgloader
      sqlite:///app/sqlite.db
      postgresql://bsnap_user:bsnap_pass@postgres:5432/bsnap_db
    depends_on:
      - postgres
    restart: "no"

volumes:
  postgres_data:
