services:
  migrate:
    build: .
    image: kpcsgt-registry.kpc.co.id/kpc-private/b-snap:v2.3.0
    env_file:
      - .env
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/app/start.sh", "migrate"]
    restart: "no"

  b-snap:
    build: .
    image: kpcsgt-registry.kpc.co.id/kpc-private/b-snap:v2.3.0
    container_name: bsnap-app
    ports:
      - "8080:8080"
    privileged: true
    cap_add:
      - NET_RAW
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./static/snapshots:/app/static/snapshots
      - ./static/videos:/app/static/videos
      - ./logs:/app/logs
      - ./archives/audit_logs:/app/archives/audit_logs
      - shared_tmp:/tmp/shared
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --workers 2 --worker-connections 1000 --timeout 60 --keep-alive 2

  scheduler:
    build: .
    image: kpcsgt-registry.kpc.co.id/kpc-private/b-snap:v2.3.0
    container_name: bsnap-scheduler
    env_file:
      - .env
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./static/snapshots:/app/static/snapshots
      - ./static/videos:/app/static/videos
      - ./logs:/app/logs
      - shared_tmp:/tmp/shared

    restart: unless-stopped
    command: ["/app/start.sh", "scheduler"]
  
  notifier:
    build: .
    image: kpcsgt-registry.kpc.co.id/kpc-private/b-snap:v2.3.0
    container_name: bsnap-notifier
    env_file:
      - .env
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    command: ["/app/start.sh", "notifier"]

  postgres: 
    image: postgres:17.5
    container_name: bsnap-postgres
    environment:
      POSTGRES_DB: bsnap_db
      POSTGRES_USER: bsnap_user
      POSTGRES_PASSWORD: bsnapDBP4ss2025
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bsnap_user -d bsnap_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: bsnap-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: wijaya.indra2196@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  shared_tmp:
