"""add sla and scheduled reports

Revision ID: 20260309_add_sla_reports
Revises: 20260309_add_job_execution_logs
Create Date: 2026-03-09 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260309_add_sla_reports'
down_revision: Union[str, None] = '20260309_add_apscheduler_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if table exists in database."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(table_name: str, index_name: str) -> bool:
    """Check if index exists on table."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create sla_reports table
    if not table_exists('sla_reports'):
        op.create_table(
            'sla_reports',
            sa.Column('id', sa.String(36), primary_key=True),
            sa.Column('camera_id', sa.String(36), sa.ForeignKey('cameras.id', ondelete='CASCADE'), nullable=False),
            sa.Column('period_start', sa.Date(), nullable=False),
            sa.Column('period_end', sa.Date(), nullable=False),
            sa.Column('uptime_percentage', sa.Float(), default=0.0),
            sa.Column('total_uptime_seconds', sa.Integer(), default=0),
            sa.Column('total_downtime_seconds', sa.Integer(), default=0),
            sa.Column('mttr_seconds', sa.Integer(), nullable=True),
            sa.Column('mtbf_seconds', sa.Integer(), nullable=True),
            sa.Column('incident_count', sa.Integer(), default=0),
            sa.Column('severity_critical', sa.Integer(), default=0),
            sa.Column('severity_major', sa.Integer(), default=0),
            sa.Column('severity_minor', sa.Integer(), default=0),
            sa.Column('compliance_status', sa.String(20), default='Unknown'),
            sa.Column('sla_threshold', sa.Float(), default=99.5),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now())
        )
        
        # Create index on camera_id for faster lookups
        op.create_index('ix_sla_reports_camera_id', 'sla_reports', ['camera_id'])
        op.create_index('ix_sla_reports_period', 'sla_reports', ['period_start', 'period_end'])
    
    # Create scheduled_reports table
    if not table_exists('scheduled_reports'):
        op.create_table(
            'scheduled_reports',
            sa.Column('id', sa.String(36), primary_key=True),
            sa.Column('name', sa.String(100), nullable=False),
            sa.Column('report_type', sa.String(20), default='health'),
            sa.Column('format', sa.String(10), default='pdf'),
            sa.Column('frequency', sa.String(20), default='weekly'),
            sa.Column('day_of_week', sa.Integer(), nullable=True),
            sa.Column('day_of_month', sa.Integer(), nullable=True),
            sa.Column('hour', sa.Integer(), default=8),
            sa.Column('timezone', sa.String(50), default='UTC'),
            sa.Column('lookback_days', sa.Integer(), default=7),
            sa.Column('include_charts', sa.Boolean(), default=True),
            sa.Column('sla_threshold', sa.Float(), default=99.5),
            sa.Column('recipients', sa.String(500), nullable=True),
            sa.Column('is_active', sa.Boolean(), default=True),
            sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('next_scheduled_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.Column('created_by', sa.String(36), sa.ForeignKey('users.id'), nullable=True)
        )
        
        op.create_index('ix_scheduled_reports_is_active', 'scheduled_reports', ['is_active'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if index_exists('scheduled_reports', 'ix_scheduled_reports_is_active'):
        op.drop_index('ix_scheduled_reports_is_active', table_name='scheduled_reports')
    if table_exists('scheduled_reports'):
        op.drop_table('scheduled_reports')
    
    if index_exists('sla_reports', 'ix_sla_reports_period'):
        op.drop_index('ix_sla_reports_period', table_name='sla_reports')
    if index_exists('sla_reports', 'ix_sla_reports_camera_id'):
        op.drop_index('ix_sla_reports_camera_id', table_name='sla_reports')
    if table_exists('sla_reports'):
        op.drop_table('sla_reports')
    # ### end Alembic commands ###
