"""encrypt nvr password

Revision ID: 20260326_encrypt_nvr
Revises: 5cedbb9e3357
Create Date: 2026-03-26 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260326_encrypt_nvr'
down_revision = '5cedbb9e3357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Change password column from String(100) to Text for encrypted data
    op.alter_column('nvr', 'password',
                    existing_type=sa.String(100),
                    type_=sa.Text,
                    existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert password column
    op.alter_column('nvr', 'password',
                    existing_type=sa.Text,
                    type_=sa.String(100),
                    existing_nullable=True)
    
    # ### end Alembic commands ###
