"""add file_hash and soft delete columns

Revision ID: 20260326_add_file_hash
Revises: 20260311_fix_snapshot_fk_cascade
Create Date: 2026-03-26 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260326_add_file_hash'
down_revision = '20260311_fix_snapshot_fk_cascade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add file_hash to snapshots
    op.add_column('snapshots', sa.Column('file_hash', sa.String(64), nullable=True))
    op.create_index('ix_snapshots_file_hash', 'snapshots', ['file_hash'])
    
    # Add deleted_at for soft delete to snapshots
    op.add_column('snapshots', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_snapshots_deleted_at', 'snapshots', ['deleted_at'])
    
    # Add file_hash to videos
    op.add_column('videos', sa.Column('file_hash', sa.String(64), nullable=True))
    op.create_index('ix_videos_file_hash', 'videos', ['file_hash'])
    
    # Add deleted_at for soft delete to videos
    op.add_column('videos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_videos_deleted_at', 'videos', ['deleted_at'])
    
    # Increase password column length to accommodate encrypted data
    op.alter_column('cameras', 'password',
                    existing_type=sa.String(255),
                    type_=sa.Text,
                    existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove indexes and columns for snapshots
    op.drop_index('ix_snapshots_deleted_at', table_name='snapshots')
    op.drop_index('ix_snapshots_file_hash', table_name='snapshots')
    op.drop_column('snapshots', 'deleted_at')
    op.drop_column('snapshots', 'file_hash')
    
    # Remove indexes and columns for videos
    op.drop_index('ix_videos_deleted_at', table_name='videos')
    op.drop_index('ix_videos_file_hash', table_name='videos')
    op.drop_column('videos', 'deleted_at')
    op.drop_column('videos', 'file_hash')
    
    # Revert password column
    op.alter_column('cameras', 'password',
                    existing_type=sa.Text,
                    type_=sa.String(255),
                    existing_nullable=True)
    
    # ### end Alembic commands ###
