"""remove_is_active_from_whitelist

Revision ID: 8048b0584a9a
Revises: 20260331_remove_lat_lon
Create Date: 2026-03-31 05:25:50.500837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8048b0584a9a'
down_revision: Union[str, None] = '20260331_remove_lat_lon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if table exists in database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(table_name: str, index_name: str) -> bool:
    """Check if index exists on table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists in table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = inspector.get_columns(table_name)
    return any(col['name'] == column_name for col in columns)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX: Safe drop apscheduler_jobs
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    
    # Alter audit_logs id column (check current type first)
    if column_exists('audit_logs', 'id'):
        op.alter_column('audit_logs', 'id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    if not index_exists('audit_logs', 'ix_audit_logs_timestamp'):
        op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    
    # Drop table comment (safe to execute even if comment doesn't exist)
    try:
        op.execute("COMMENT ON TABLE audit_logs IS NULL")
    except Exception:
        pass
    
    # Alter camera_health columns (remove comments)
    if column_exists('camera_health', 'alert_cooldown_until'):
        op.alter_column('camera_health', 'alert_cooldown_until',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment=None,
                   existing_nullable=True)
    if column_exists('camera_health', 'last_alert_reason'):
        op.alter_column('camera_health', 'last_alert_reason',
                   existing_type=sa.VARCHAR(),
                   comment=None,
                   existing_nullable=True)
    
    if index_exists('camera_health', 'ix_camera_health_alert_cooldown_until'):
        op.drop_index(op.f('ix_camera_health_alert_cooldown_until'), table_name='camera_health')
    
    # Alter cameras columns (remove comments)
    if column_exists('cameras', 'notification_fail_count'):
        op.alter_column('cameras', 'notification_fail_count',
                   existing_type=sa.INTEGER(),
                   comment=None,
                   existing_nullable=False,
                   existing_server_default=sa.text('0'))
    if column_exists('cameras', 'notification_suppressed_until'):
        op.alter_column('cameras', 'notification_suppressed_until',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment=None,
                   existing_nullable=True)
    if column_exists('cameras', 'last_notification_at'):
        op.alter_column('cameras', 'last_notification_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment=None,
                   existing_nullable=True)
    
    if index_exists('cameras', 'ix_cameras_notification_suppressed_until'):
        op.drop_index(op.f('ix_cameras_notification_suppressed_until'), table_name='cameras')
    
    # Drop column whatsapp_whitelist.is_active (check existence)
    if column_exists('whatsapp_whitelist', 'is_active'):
        op.drop_column('whatsapp_whitelist', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add column back
    if not column_exists('whatsapp_whitelist', 'is_active'):
        op.add_column('whatsapp_whitelist', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    
    if not index_exists('cameras', 'ix_cameras_notification_suppressed_until'):
        op.create_index(op.f('ix_cameras_notification_suppressed_until'), 'cameras', ['notification_suppressed_until'], unique=False)
    
    # Restore comments
    if column_exists('cameras', 'last_notification_at'):
        op.alter_column('cameras', 'last_notification_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment='Timestamp of last notification attempt for deduplication',
                   existing_nullable=True)
    if column_exists('cameras', 'notification_suppressed_until'):
        op.alter_column('cameras', 'notification_suppressed_until',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment='Circuit breaker: timestamp when notification suppression ends',
                   existing_nullable=True)
    if column_exists('cameras', 'notification_fail_count'):
        op.alter_column('cameras', 'notification_fail_count',
                   existing_type=sa.INTEGER(),
                   comment='Circuit breaker: consecutive notification failures (max 3 before suppression)',
                   existing_nullable=False,
                   existing_server_default=sa.text('0'))
    
    if not index_exists('camera_health', 'ix_camera_health_alert_cooldown_until'):
        op.create_index(op.f('ix_camera_health_alert_cooldown_until'), 'camera_health', ['alert_cooldown_until'], unique=False)
    
    if column_exists('camera_health', 'last_alert_reason'):
        op.alter_column('camera_health', 'last_alert_reason',
                   existing_type=sa.VARCHAR(),
                   comment='Reason for last alert sent (for deduplication)',
                   existing_nullable=True)
    if column_exists('camera_health', 'alert_cooldown_until'):
        op.alter_column('camera_health', 'alert_cooldown_until',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment='Timestamp when next alert can be sent (prevents flooding)',
                   existing_nullable=True)
    
    try:
        op.create_table_comment(
            'audit_logs',
            'P2-001: Append-only audit log. Records cannot be updated or deleted.',
            existing_comment=None,
            schema=None
        )
    except Exception:
        pass
    
    if index_exists('audit_logs', 'ix_audit_logs_timestamp'):
        op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    
    if column_exists('audit_logs', 'id'):
        op.alter_column('audit_logs', 'id',
                   existing_type=sa.BigInteger(),
                   type_=sa.INTEGER(),
                   existing_nullable=False,
                   autoincrement=True)
    
    # FIX: Safe recreate apscheduler_jobs
    if not table_exists('apscheduler_jobs'):
        op.create_table('apscheduler_jobs',
            sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
            sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
            sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
        )
        op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###