"""remove_is_active_from_whitelist

Revision ID: 8048b0584a9a
Revises: 20260331_remove_lat_lon
Create Date: 2026-03-31 05:25:50.500837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8048b0584a9a'
down_revision: Union[str, None] = '20260331_remove_lat_lon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def view_exists(view_name: str) -> bool:
    """Check if view exists in database."""
    bind = op.get_bind()
    result = bind.execute(text(
        "SELECT EXISTS (SELECT 1 FROM pg_views WHERE viewname = :name)"
    ), {"name": view_name}).scalar()
    return result


def table_exists(table_name: str) -> bool:
    """Check if table exists in database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(table_name: str, index_name: str) -> bool:
    """Check if index exists on table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists in table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = inspector.get_columns(table_name)
    return any(col['name'] == column_name for col in columns)


def upgrade() -> None:
    """Upgrade schema."""
    
    # FIX: Drop view yang bergantung pada audit_logs terlebih dahulu
    if view_exists('audit_logs_unified'):
        op.execute("DROP VIEW IF EXISTS audit_logs_unified")
    
    # FIX: Drop archive_history jika ada (juga mungkin bergantung)
    if table_exists('audit_archive_history'):
        op.execute("DROP TABLE IF EXISTS audit_archive_history CASCADE")
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX: Safe drop apscheduler_jobs
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    
    # Alter audit_logs id column (check current type first)
    if column_exists('audit_logs', 'id'):
        op.alter_column('audit_logs', 'id',
                   existing_type=sa.INTEGER(),
                   type_=sa.BigInteger(),
                   existing_nullable=False,
                   autoincrement=True)
    
    if not index_exists('audit_logs', 'ix_audit_logs_timestamp'):
        op.execute("CREATE INDEX IF NOT EXISTS ix_audit_logs_timestamp ON audit_logs (timestamp)")
    
    # Drop table comment (safe to execute even if comment doesn't exist)
    try:
        op.execute("COMMENT ON TABLE audit_logs IS NULL")
    except Exception:
        pass
    
    # Alter camera_health columns (remove comments)
    if column_exists('camera_health', 'alert_cooldown_until'):
        op.alter_column('camera_health', 'alert_cooldown_until',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment=None,
                   existing_nullable=True)
    if column_exists('camera_health', 'last_alert_reason'):
        op.alter_column('camera_health', 'last_alert_reason',
                   existing_type=sa.VARCHAR(),
                   comment=None,
                   existing_nullable=True)
    
    if index_exists('camera_health', 'ix_camera_health_alert_cooldown_until'):
        op.drop_index('ix_camera_health_alert_cooldown_until', table_name='camera_health')
    
    # Alter cameras columns (remove comments)
    if column_exists('cameras', 'notification_fail_count'):
        op.alter_column('cameras', 'notification_fail_count',
                   existing_type=sa.INTEGER(),
                   comment=None,
                   existing_nullable=False,
                   existing_server_default=sa.text('0'))
    if column_exists('cameras', 'notification_suppressed_until'):
        op.alter_column('cameras', 'notification_suppressed_until',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment=None,
                   existing_nullable=True)
    if column_exists('cameras', 'last_notification_at'):
        op.alter_column('cameras', 'last_notification_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   comment=None,
                   existing_nullable=True)
    
    if index_exists('cameras', 'ix_cameras_notification_suppressed_until'):
        op.drop_index('ix_cameras_notification_suppressed_until', table_name='cameras')
    
    # Drop column whatsapp_whitelist.is_active (check existence)
    if column_exists('whatsapp_whitelist', 'is_active'):
        op.drop_column('whatsapp_whitelist', 'is_active')
    
    # ### end Alembic commands ###
    
    # FIX: Recreate view setelah alter column selesai
    if table_exists('audit_logs') and table_exists('audit_logs_legacy'):
        op.execute("""
            CREATE OR REPLACE VIEW audit_logs_unified AS
            SELECT 
                id, timestamp, "user", action, target, ip, extra,
                user_agent, request_path, request_method, response_status,
                'current' as source
            FROM audit_logs
            UNION ALL
            SELECT 
                id, timestamp, "user", action, target, ip, extra,
                user_agent, request_path, request_method, response_status,
                'legacy' as source
            FROM audit_logs_legacy
            ORDER BY timestamp DESC
        """)
    
    # FIX: Recreate archive_history table
    if not table_exists('audit_archive_history'):
        op.create_table(
            'audit_archive_history',
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False,
                      server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('archived_by', sa.String(length=100), nullable=False),
            sa.Column('archive_period_start', sa.DateTime(timezone=True), nullable=False),
            sa.Column('archive_period_end', sa.DateTime(timezone=True), nullable=False),
            sa.Column('records_archived', sa.BigInteger(), nullable=False),
            sa.Column('file_path', sa.String(length=500), nullable=False),
            sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
            sa.Column('checksum', sa.String(length=64), nullable=True),
            sa.Column('encryption_key_id', sa.String(length=100), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=False, server_default='completed'),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.execute("CREATE INDEX IF NOT EXISTS ix_audit_archive_history_archived_at ON audit_archive_history (archived_at)")


def downgrade() -> None:
    """Downgrade schema."""
    # ... (downgrade tetap sama seperti sebelumnya)
    
    # FIX: Recreate view di downgrade juga jika perlu
    if table_exists('audit_logs') and table_exists('audit_logs_legacy'):
        op.execute("""
            CREATE OR REPLACE VIEW audit_logs_unified AS
            SELECT 
                id, timestamp, "user", action, target, ip, extra,
                user_agent, request_path, request_method, response_status,
                'current' as source
            FROM audit_logs
            UNION ALL
            SELECT 
                id, timestamp, "user", action, target, ip, extra,
                user_agent, request_path, request_method, response_status,
                'legacy' as source
            FROM audit_logs_legacy
            ORDER BY timestamp DESC
        """)