"""remove_is_active_from_whitelist

Revision ID: 8048b0584a9a
Revises: 20260331_remove_lat_lon
Create Date: 2026-03-31 05:25:50.500837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8048b0584a9a'
down_revision: Union[str, None] = '20260331_remove_lat_lon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_table_comment(
        'audit_logs',
        existing_comment='P2-001: Append-only audit log. Records cannot be updated or deleted.',
        schema=None
    )
    op.alter_column('camera_health', 'alert_cooldown_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when next alert can be sent (prevents flooding)',
               existing_nullable=True)
    op.alter_column('camera_health', 'last_alert_reason',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Reason for last alert sent (for deduplication)',
               existing_nullable=True)
    op.drop_index(op.f('ix_camera_health_alert_cooldown_until'), table_name='camera_health')
    op.alter_column('cameras', 'notification_fail_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Circuit breaker: consecutive notification failures (max 3 before suppression)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cameras', 'notification_suppressed_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Circuit breaker: timestamp when notification suppression ends',
               existing_nullable=True)
    op.alter_column('cameras', 'last_notification_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of last notification attempt for deduplication',
               existing_nullable=True)
    op.drop_index(op.f('ix_cameras_notification_suppressed_until'), table_name='cameras')
    op.drop_column('whatsapp_whitelist', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_whitelist', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_cameras_notification_suppressed_until'), 'cameras', ['notification_suppressed_until'], unique=False)
    op.alter_column('cameras', 'last_notification_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last notification attempt for deduplication',
               existing_nullable=True)
    op.alter_column('cameras', 'notification_suppressed_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Circuit breaker: timestamp when notification suppression ends',
               existing_nullable=True)
    op.alter_column('cameras', 'notification_fail_count',
               existing_type=sa.INTEGER(),
               comment='Circuit breaker: consecutive notification failures (max 3 before suppression)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_camera_health_alert_cooldown_until'), 'camera_health', ['alert_cooldown_until'], unique=False)
    op.alter_column('camera_health', 'last_alert_reason',
               existing_type=sa.VARCHAR(),
               comment='Reason for last alert sent (for deduplication)',
               existing_nullable=True)
    op.alter_column('camera_health', 'alert_cooldown_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when next alert can be sent (prevents flooding)',
               existing_nullable=True)
    op.create_table_comment(
        'audit_logs',
        'P2-001: Append-only audit log. Records cannot be updated or deleted.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
