"""add_safety_classification_p2_002

Revision ID: 8a53b8bab616
Revises: f3170d221195
Create Date: 2026-03-27 08:54:12.568331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a53b8bab616'
down_revision: Union[str, None] = 'f3170d221195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('safety_classification', sa.String(length=20), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'safety_classification')
    # ### end Alembic commands ###
