"""add_p2_001_append_only_audit_log

Revision ID: a0b22741533a
Revises: 8a53b8bab616
Create Date: 2026-03-28 02:09:47.383775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0b22741533a'
down_revision: Union[str, None] = '8a53b8bab616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('request_path', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('request_method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('response_status', sa.Integer(), nullable=True))
    op.alter_column('audit_logs', 'extra',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_target'), 'audit_logs', ['target'], unique=False)
    op.create_index(op.f('ix_audit_logs_user'), 'audit_logs', ['user'], unique=False)
    
    # P2-001: Create triggers to enforce append-only behavior on audit_logs
    op.execute("""
        -- Create function to prevent DELETE on audit_logs
        CREATE OR REPLACE FUNCTION prevent_audit_log_delete()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Audit logs cannot be deleted. This is an append-only table (P2-001).';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        
        -- Create trigger to prevent DELETE
        DROP TRIGGER IF EXISTS audit_log_prevent_delete ON audit_logs;
        CREATE TRIGGER audit_log_prevent_delete
            BEFORE DELETE ON audit_logs
            FOR EACH ROW
            EXECUTE FUNCTION prevent_audit_log_delete();
    """)
    
    op.execute("""
        -- Create function to prevent UPDATE on audit_logs
        CREATE OR REPLACE FUNCTION prevent_audit_log_update()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Audit logs cannot be modified. This is an append-only table (P2-001).';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        
        -- Create trigger to prevent UPDATE
        DROP TRIGGER IF EXISTS audit_log_prevent_update ON audit_logs;
        CREATE TRIGGER audit_log_prevent_update
            BEFORE UPDATE ON audit_logs
            FOR EACH ROW
            EXECUTE FUNCTION prevent_audit_log_update();
    """)
    
    # Add table comment
    op.execute("COMMENT ON TABLE audit_logs IS 'P2-001: Append-only audit log. Records cannot be updated or deleted.'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove triggers and functions first
    op.execute("DROP TRIGGER IF EXISTS audit_log_prevent_delete ON audit_logs")
    op.execute("DROP TRIGGER IF EXISTS audit_log_prevent_update ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_delete()")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_update()")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'extra',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'response_status')
    op.drop_column('audit_logs', 'request_method')
    op.drop_column('audit_logs', 'request_path')
    op.drop_column('audit_logs', 'user_agent')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
