"""add email_templates table

Revision ID: a3366d14c9a4
Revises: 8048b0584a9a
Create Date: 2026-04-01 03:48:00.748489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3366d14c9a4'
down_revision: Union[str, None] = '8048b0584a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if table exists in database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(table_name: str, index_name: str) -> bool:
    """Check if index exists on table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create email_templates table (check existence)
    if not table_exists('email_templates'):
        op.create_table('email_templates',
            sa.Column('template_type', sa.String(length=50), nullable=False),
            sa.Column('subject', sa.String(length=500), nullable=False),
            sa.Column('plain_body', sa.Text(), nullable=False),
            sa.Column('html_body', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('template_type')
        )
    
    # FIX: Safe drop apscheduler_jobs
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX: Safe recreate apscheduler_jobs
    if not table_exists('apscheduler_jobs'):
        op.create_table('apscheduler_jobs',
            sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
            sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
            sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
        )
        op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    
    if table_exists('email_templates'):
        op.drop_table('email_templates')
    # ### end Alembic commands ###