"""initial migration

Revision ID: aff625e314d6
Revises: 
Create Date: 2025-06-19 10:43:06.631747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff625e314d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_camera_daily_stats_id', table_name='camera_daily_stats')
    op.drop_table('camera_daily_stats')
    op.drop_table('camera_groups')
    op.drop_table('camera_health')
    op.drop_table('health_check_status')
    op.drop_table('nvr')
    op.drop_table('users')
    op.drop_index('ix_snapshot_logs_id', table_name='snapshot_logs')
    op.drop_table('snapshot_logs')
    op.drop_table('cameras')
    op.drop_table('camera_stats')
    op.drop_table('audit_logs')
    op.drop_table('configurations')
    op.drop_table('snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('camera_name', sa.VARCHAR(), nullable=False),
    sa.Column('camera_ip', sa.VARCHAR(), nullable=False),
    sa.Column('camera_port', sa.INTEGER(), nullable=False),
    sa.Column('camera_location', sa.VARCHAR(), nullable=True),
    sa.Column('camera_group', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('resolution', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('target', sa.VARCHAR(), nullable=False),
    sa.Column('ip', sa.VARCHAR(), nullable=True),
    sa.Column('extra', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('snapshot_count', sa.INTEGER(), nullable=True),
    sa.Column('video_count', sa.INTEGER(), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('uptime_percentage', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('hostname', sa.VARCHAR(), nullable=False),
    sa.Column('previous_name', sa.VARCHAR(), nullable=True),
    sa.Column('ip', sa.VARCHAR(), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('previous_latitude', sa.FLOAT(), nullable=True),
    sa.Column('previous_longitude', sa.FLOAT(), nullable=True),
    sa.Column('asset_no', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['camera_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('id')
    )
    op.create_table('snapshot_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('camera_name', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['camera_name'], ['cameras.hostname'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_logs_id', 'snapshot_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('token', sa.VARCHAR(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['camera_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('nvr',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=25), nullable=True),
    sa.Column('division', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=15), nullable=True),
    sa.Column('asset_no', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('health_check_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_running', sa.BOOLEAN(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('total_cameras', sa.INTEGER(), nullable=True),
    sa.Column('completed_cameras', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_health',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('latency', sa.INTEGER(), nullable=True),
    sa.Column('checked', sa.DATETIME(), nullable=False),
    sa.Column('last_online', sa.DATETIME(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('nvr_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['nvr_id'], ['nvr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('camera_daily_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('camera_name', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('snapshot_count', sa.INTEGER(), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('uptime_seconds', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_camera_daily_stats_id', 'camera_daily_stats', ['id'], unique=False)
    # ### end Alembic commands ###
