"""drop_orphaned_files_table

Revision ID: b29ff945dac6
Revises: 20260326_encrypt_nvr
Create Date: 2026-03-26 08:41:53.270867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'b29ff945dac6'
down_revision: Union[str, None] = '20260326_encrypt_nvr'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if table exists in database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(table_name: str, index_name: str) -> bool:
    """Check if index exists on table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def constraint_exists(table_name: str, constraint_name: str) -> bool:
    """Check if unique constraint exists."""
    bind = op.get_bind()
    inspector = inspect(bind)
    constraints = inspector.get_unique_constraints(table_name)
    return any(c['name'] == constraint_name for c in constraints)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX 1: Only drop apscheduler_jobs if it exists (may not exist in this branch)
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    
    # FIX 2: Safely drop orphaned_files table and its indexes
    if table_exists('orphaned_files'):
        # Drop indexes first (check existence)
        if index_exists('orphaned_files', 'ix_orphaned_files_status'):
            op.drop_index(op.f('ix_orphaned_files_status'), table_name='orphaned_files')
        
        # Note: ix_orphaned_files_camera_id might not exist in some versions, check carefully
        indexes = inspect(op.get_bind()).get_indexes('orphaned_files')
        for idx in indexes:
            if idx['name'] in ['ix_orphaned_files_camera_id', 'idx_orphaned_camera_id']:
                op.drop_index(idx['name'], table_name='orphaned_files')
        
        if index_exists('orphaned_files', 'ix_orphaned_files_file_path'):
            op.drop_index(op.f('ix_orphaned_files_file_path'), table_name='orphaned_files')
        
        # Drop table
        op.drop_table('orphaned_files')
    
    # FIX 3: Create unique constraints with explicit names (not None)
    # Note: These constraints might already exist, check first
    if table_exists('camera_status_change_log'):
        if not constraint_exists('camera_status_change_log', 'uq_camera_status_change_log_id'):
            op.create_unique_constraint(
                'uq_camera_status_change_log_id', 
                'camera_status_change_log', 
                ['id']
            )
    
    if table_exists('cameras'):
        if not constraint_exists('cameras', 'uq_cameras_id'):
            op.create_unique_constraint('uq_cameras_id', 'cameras', ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX 4: Drop constraints by specific name (not None)
    if table_exists('cameras'):
        # Try to drop by specific name used in upgrade
        try:
            op.drop_constraint('uq_cameras_id', 'cameras', type_='unique')
        except Exception:
            # If named constraint failed, try to find and drop any unique constraint on 'id'
            pass
    
    if table_exists('camera_status_change_log'):
        try:
            op.drop_constraint('uq_camera_status_change_log_id', 'camera_status_change_log', type_='unique')
        except Exception:
            pass
    
    # FIX 5: Recreate orphaned_files table only if not exists
    if not table_exists('orphaned_files'):
        op.create_table(
            'orphaned_files',
            sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
            sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
            sa.Column('camera_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
            sa.Column('detected_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
            sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
            sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('orphaned_files_pkey'))
        )
        
        # Recreate indexes
        op.create_index(
            op.f('ix_orphaned_files_file_path'), 
            'orphaned_files', 
            ['file_path'], 
            unique=True
        )
        op.create_index(
            op.f('ix_orphaned_files_status'), 
            'orphaned_files', 
            ['status'], 
            unique=False
        )
        op.create_index(
            op.f('ix_orphaned_files_camera_id'), 
            'orphaned_files', 
            ['camera_id'], 
            unique=False
        )
    
    # FIX 6: Recreate apscheduler_jobs only if not exists
    if not table_exists('apscheduler_jobs'):
        op.create_table(
            'apscheduler_jobs',
            sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
            sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
            sa.Column('job_state', sa.dialects.postgresql.BYTEA(), autoincrement=False, nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
        )
        op.create_index(
            op.f('ix_apscheduler_jobs_next_run_time'), 
            'apscheduler_jobs', 
            ['next_run_time'], 
            unique=False
        )
    
    # ### end Alembic commands ###