"""drop_orphaned_files_table

Revision ID: b29ff945dac6
Revises: 20260326_encrypt_nvr
Create Date: 2026-03-26 08:41:53.270867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b29ff945dac6'
down_revision: Union[str, None] = '20260326_encrypt_nvr'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('ix_orphaned_files_camera_id'), table_name='orphaned_files')
    op.drop_index(op.f('ix_orphaned_files_file_path'), table_name='orphaned_files')
    op.drop_index(op.f('ix_orphaned_files_status'), table_name='orphaned_files')
    op.drop_table('orphaned_files')
    op.create_unique_constraint(None, 'camera_status_change_log', ['id'])
    op.create_unique_constraint(None, 'cameras', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='unique')
    op.drop_constraint(None, 'camera_status_change_log', type_='unique')
    op.create_table('orphaned_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('orphaned_files_pkey'))
    )
    op.create_index(op.f('ix_orphaned_files_status'), 'orphaned_files', ['status'], unique=False)
    op.create_index(op.f('ix_orphaned_files_file_path'), 'orphaned_files', ['file_path'], unique=True)
    op.create_index(op.f('ix_orphaned_files_camera_id'), 'orphaned_files', ['camera_id'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
