"""Add user tokens, camera status log, and drop user sessions

Revision ID: c77a8f33d36f
Revises: 28dd74ec28bc
Create Date: 2025-07-10 12:22:15.096693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77a8f33d36f'
down_revision: Union[str, None] = '28dd74ec28bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    
    # Add 'web_tokens' and 'api_tokens' columns to 'users' table
    op.add_column('users', sa.Column('web_tokens', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('api_tokens', sa.JSON(), nullable=True))

    # Add 'checked' column to 'camera_daily_stats' table
    op.add_column('camera_daily_stats', sa.Column('checked', sa.DateTime(timezone=True), nullable=True))
    # Update existing rows to have a default value for the new non-nullable column
    op.execute("UPDATE camera_daily_stats SET checked = NOW() WHERE checked IS NULL")
    op.alter_column('camera_daily_stats', 'checked', nullable=False)


    # Create 'camera_status_change_log' table
    op.create_table('camera_status_change_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_since_last_change', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    # Drop 'user_sessions' table
    op.drop_table('user_sessions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###

    # Create 'user_sessions' table again
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_sessions_pkey'),
    sa.UniqueConstraint('token', name='user_sessions_token_key')
    )

    # Drop 'camera_status_change_log' table
    op.drop_table('camera_status_change_log')

    # Drop 'checked' column from 'camera_daily_stats' table
    op.drop_column('camera_daily_stats', 'checked')

    # Drop 'web_tokens' and 'api_tokens' columns from 'users' table
    op.drop_column('users', 'api_tokens')
    op.drop_column('users', 'web_tokens')

    # ### end Alembic commands ###
