"""add is_flipped column to cameras

Revision ID: da0483da8f95
Revises: ed2356cb250c
Create Date: 2025-07-31 02:30:23.757054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0483da8f95'
down_revision: Union[str, None] = 'ed2356cb250c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('is_flipped', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Remove default if you don’t want it after migration
    op.alter_column('cameras', 'is_flipped', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('cameras', 'is_flipped')