"""add_retention_hold_p2_001

Revision ID: f3170d221195
Revises: b29ff945dac6
Create Date: 2026-03-27 08:44:04.021303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3170d221195'
down_revision: Union[str, None] = 'b29ff945dac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('snapshots', sa.Column('retention_hold', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('snapshots', sa.Column('retention_hold_reason', sa.String(length=500), nullable=True))
    op.add_column('snapshots', sa.Column('retention_hold_by', sa.String(length=100), nullable=True))
    op.add_column('snapshots', sa.Column('retention_hold_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('retention_hold', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('videos', sa.Column('retention_hold_reason', sa.String(length=500), nullable=True))
    op.add_column('videos', sa.Column('retention_hold_by', sa.String(length=100), nullable=True))
    op.add_column('videos', sa.Column('retention_hold_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'retention_hold_at')
    op.drop_column('videos', 'retention_hold_by')
    op.drop_column('videos', 'retention_hold_reason')
    op.drop_column('videos', 'retention_hold')
    op.drop_column('snapshots', 'retention_hold_at')
    op.drop_column('snapshots', 'retention_hold_by')
    op.drop_column('snapshots', 'retention_hold_reason')
    op.drop_column('snapshots', 'retention_hold')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
