"""add_retention_hold_p2_001

Revision ID: f3170d221195
Revises: b29ff945dac6
Create Date: 2026-03-27 08:44:04.021303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3170d221195'
down_revision: Union[str, None] = 'b29ff945dac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if table exists in database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def index_exists(table_name: str, index_name: str) -> bool:
    """Check if index exists on table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX: Safe drop apscheduler_jobs
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    
    # Add retention hold columns to snapshots
    if not column_exists('snapshots', 'retention_hold'):
        op.add_column('snapshots', sa.Column('retention_hold', sa.Boolean(), server_default='0', nullable=False))
    if not column_exists('snapshots', 'retention_hold_reason'):
        op.add_column('snapshots', sa.Column('retention_hold_reason', sa.String(length=500), nullable=True))
    if not column_exists('snapshots', 'retention_hold_by'):
        op.add_column('snapshots', sa.Column('retention_hold_by', sa.String(length=100), nullable=True))
    if not column_exists('snapshots', 'retention_hold_at'):
        op.add_column('snapshots', sa.Column('retention_hold_at', sa.DateTime(timezone=True), nullable=True))
    
    # Add retention hold columns to videos
    if not column_exists('videos', 'retention_hold'):
        op.add_column('videos', sa.Column('retention_hold', sa.Boolean(), server_default='0', nullable=False))
    if not column_exists('videos', 'retention_hold_reason'):
        op.add_column('videos', sa.Column('retention_hold_reason', sa.String(length=500), nullable=True))
    if not column_exists('videos', 'retention_hold_by'):
        op.add_column('videos', sa.Column('retention_hold_by', sa.String(length=100), nullable=True))
    if not column_exists('videos', 'retention_hold_at'):
        op.add_column('videos', sa.Column('retention_hold_at', sa.DateTime(timezone=True), nullable=True))
    
    # ### end Alembic commands ###


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists in table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = inspector.get_columns(table_name)
    return any(col['name'] == column_name for col in columns)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop columns videos
    if column_exists('videos', 'retention_hold_at'):
        op.drop_column('videos', 'retention_hold_at')
    if column_exists('videos', 'retention_hold_by'):
        op.drop_column('videos', 'retention_hold_by')
    if column_exists('videos', 'retention_hold_reason'):
        op.drop_column('videos', 'retention_hold_reason')
    if column_exists('videos', 'retention_hold'):
        op.drop_column('videos', 'retention_hold')
    
    # Drop columns snapshots
    if column_exists('snapshots', 'retention_hold_at'):
        op.drop_column('snapshots', 'retention_hold_at')
    if column_exists('snapshots', 'retention_hold_by'):
        op.drop_column('snapshots', 'retention_hold_by')
    if column_exists('snapshots', 'retention_hold_reason'):
        op.drop_column('snapshots', 'retention_hold_reason')
    if column_exists('snapshots', 'retention_hold'):
        op.drop_column('snapshots', 'retention_hold')
    
    # FIX: Safe recreate apscheduler_jobs
    if not table_exists('apscheduler_jobs'):
        op.create_table('apscheduler_jobs',
            sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
            sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
            sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
            sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
        )
        op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    
    # ### end Alembic commands ###