# Routes package
# Import all route modules here for easy access

from app.routes import (
    admin,
    auth,
    audit,
    audit_log,
    cameras,
    config,
    dev_docs,
    docs,
    email_logs,
    group_recipients,
    health,
    insights,
    logs,
    maps,
    notifications,
    nvrs,
    ping,
    resolve_ip,
    setup,
    snap_gallery,
    snapshots,
    stats,
    toast_demo,
    user_management,
    videos,
    wa_webhook,
    whitelist,
)

__all__ = [
    "admin",
    "auth",
    "audit",
    "audit_log",
    "cameras",
    "config",
    "dev_docs",
    "docs",
    "email_logs",
    "group_recipients",
    "health",
    "insights",
    "logs",
    "maps",
    "notifications",
    "nvrs",
    "ping",
    "resolve_ip",
    "setup",
    "snap_gallery",
    "snapshots",
    "stats",
    "toast_demo",
    "user_management",
    "videos",
    "wa_webhook",
    "whitelist",
]
